### ISSUE TITLE
AWS authentication needed

### ISSUE THREAD

**Issue by Baaart25** [DavidNemeskey/cc_corpus#22]
Since April using the S3 API to access data from the Amazon cloud requires authentication. So unsigned access to the CommonCrawl is disabled, therefore the _download_pages.py_ script is not working because of the unsigned config.
Removing the Config is enough to make it work.

https://commoncrawl.org/2022/03/introducing-cloudfront-access-to-common-crawl-data/

**Comment by DavidNemeskey** [comment]
Resolved via #27.
