### ISSUE TITLE
Resulting (downloaded & filtered/processed) dataset available?

### ISSUE THREAD

**Issue by arpitest** [DavidNemeskey/cc_corpus#48]
I've found this but looks very old:
https://nessie.ilab.sztaki.hu/~ndavid/Webcorpus2_text/

do you have an updated version from 2022/2023 commoncrawl and using the updated scripts/processing pipeline from this repo?

**Comment by DavidNemeskey** [comment]
@arpitest We do, but we are not allowed to publicly share it due to [legal reasons](https://gdpr.eu/). research
